### ISSUE TITLE
It would be nice to improve that

### ISSUE THREAD

**Issue by testrustic** [Wikidepia/InstaFix#24]
I don't like that when sending a publication with several photos I put together 1 single photo with the 4 publications.

**Comment by Wikidepia** [comment]
Do you have example of that?

**Comment by testrustic** [comment]
![image](https://github.com/Wikidepia/InstaFix/assets/137369571/012ce792-9613-42d9-9af0-06b09c47ef3f)

![image](https://github.com/Wikidepia/InstaFix/assets/137369571/d9712d24-40d4-44ff-96ea-999a2721f649)

**Comment by testrustic** [comment]
Another problem I found is that the stories are sent as images if they are videos.

**Comment by Wikidepia** [comment]
> ![image](https://user-images.githubusercontent.com/137369571/252099604-d9712d24-40d4-44ff-96ea-999a2721f649.png)

If you want to only get the first one you can do https://www.ddxx.com/p/CufXUrDJR_d/1. Unfortunately, there is currently no way to achieve a similar carousel functionality as seen on Instagram.

> Another problem I found is that the stories are sent as images if they are videos.

It's unlikely that video stories will be supported in the near future, since accessing stories without an account is not possible.
